version: "3.8"
services:
  postgres:
    container_name: postgres_JPAsadaa
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CA214DB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_JPAsadaa
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jpaa@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

